install mysql

diff --git a/07-install-mySQL b/07-install-mySQL
--- a/07-install-mySQL
+++ b/07-install-mySQL
@@ -5,9 +5,17 @@ ID=$(id -u)
 if [ $ID -ne 0 ]
 then
     echo "ERROR:: Please run this script with root access"
+    exit 1
 else
     echo "You are root user"
 fi    
 
 yum install mysql -y
 
+if [ $? -ne 0 ]
+then
+    echo "ERROR:: Installating MySQL is failed"
+    exit 1
+else
+    echo "Installing MySQL SUCCESS"
+fi
